const banco = [/* {nome: "LUCCA DUARTE", ferias: 6, caixa: 9534}, 
        {nome: "MATHEUS FERNANDES", ferias: 0, caixa: 9536},
        {nome: "RENAN OLIVEIRA", ferias: 6, caixa: 9516} */
        {nome: "ALESSANDRA", ferias: 0, caixa: 6521},
        {nome: "ALEXANDRA", ferias: 0, caixa: 6588},
        {nome: "ALINE DA SILVA", ferias: 0, caixa: 9519},
        {nome: "AMANDA MOURA", ferias: 0, caixa: 7568},
        {nome: "AMANDA NASCIMENTO", ferias: 0, caixa: 6385},
        {nome: "ANA PAULA", ferias: 6, caixa: 6584},
        {nome: "ANGÉLICA BEZERRA", ferias: 0, caixa: 7165},
        {nome: "CAIO HENRIQUE", ferias: 0, caixa: 7809},
        {nome: "CAMILA DE OLIVEIRA", ferias: 0, caixa: 9371},
        {nome: "CARLOS EDUARDO NERY", ferias: 0, caixa: 7801},
        {nome: "CRISTIANE TEIXEIRA", ferias: 0, caixa: 9980},
        {nome: "DANIELA VIANA", ferias: 0, caixa: 6587},
        {nome: "ELLEN GUSMÃO", ferias: 0, caixa: 9370},
        {nome: "ELLEN SANTANA", ferias: 0, caixa: 9524},
        {nome: "EMANOELLE MENDONÇA", ferias: 0, caixa: 9518},
        {nome: "ERIC RIAN", ferias: 6, caixa: 6473},
        {nome: "ERICA COUTINHO", ferias: 0, caixa: 6595},
        {nome: "FABRICIO EBONE", ferias: 0, caixa: 9532},
        {nome: "GABRIEL ARTHUR", ferias: 0, caixa: 9533},
        {nome: "GABRIEL MENINO", ferias: 0, caixa: 5794},
        {nome: "GABRIELLE OLIVEIRA", ferias: 0, caixa: 6377},
        {nome: "GABRIELLE VELOSO", ferias: 0, caixa: 9523},
        {nome: "GIOVANE SILVA", ferias: 0, caixa: 9979},
        {nome: "GIOVANNA DINIZ", ferias: 0, caixa: 5798},
        {nome: "GIULIA LOPEZ", ferias: 0, caixa: 9520},
        {nome: "HENRIQUE LUCIANO", ferias: 0, caixa: 9602},
        {nome: "ISABELLA DEZIDERIO", ferias: 0, caixa: 9374},
        {nome: "ISABELLE DA SILVA", ferias: 0, caixa: 8924},
        {nome: "ISRAEL", ferias: 0, caixa: 9901},
        {nome: "JACIEL", ferias: 0, caixa: 6474},
        {nome: "JADE ENDYLE", ferias: 0, caixa: 9372},
        {nome: "JAIRE MARIA", ferias: 0, caixa: 9769},
        {nome: "JOÃO FERNANDO RICI", ferias: 0, caixa: 9515},
        {nome: "LARISSA FRANCO", ferias: 0, caixa: 7821},
        {nome: "LAURA SILVA", ferias: 0, caixa: 9525},
        {nome: "LEANDRA CALDEIRA", ferias: 0, caixa: 9365},
        {nome: "LOUISE", ferias: 0, caixa: 10092},
        {nome: "LUANA", ferias: 0, caixa: 6472},
        {nome: "MARCO ANTONIO SILVA", ferias: 0, caixa: 9768},
        {nome: "MATEUS MACHADO", ferias: 0, caixa: 9522},
        {nome: "MATHEUS CAVALCANTE", ferias: 0, caixa: 6559},
        {nome: "MILENA MEIRELES", ferias: 0, caixa: 9526},
        {nome: "NATASHA ROOSEVELT", ferias: 0, caixa: 7822},
        {nome: "PEDRO HENRIQUE", ferias: 0, caixa: 7113},
        {nome: "QUÉSYA ADRIANA", ferias: 0, caixa: 9529},
        {nome: "RODOLFO MOREIRA", ferias: 0, caixa: 7115},
        {nome: "STEFANI MOTA DA COSTA", ferias: 6, caixa: 6378},
        {nome: "SUZANA SANTOS", ferias: 0, caixa: 7569},
        {nome: "THALICIA DE OLIVEIRA", ferias: 0, caixa: 7738},
        {nome: "THIAGO JACOB", ferias: 0, caixa: 7311},
        {nome: "VALMOR LUIZ", ferias: 0, caixa: 9375},
        {nome: "VERONICA GAGLIARDI", ferias: 0, caixa: 9770}
];

module.exports = banco;